# Generated by Django 2.2.1 on 2019-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='Cedula',
            field=models.PositiveIntegerField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
